### ISSUE TITLE
Task 'npm:init' is not in your shipitfile

### ISSUE THREAD

**Issue by jwhitmarsh** [shipitjs/grunt-shipit#59]
Keep getting this error trying to use `shipit-npm` module. That module is designed to work with grunt or shipit (using the gruntOrShipit method in `shipit-util`). Any ideas would be welcome!

```
Running "deploy:init" task
Task 'npm:init' is not in your shipitfile
Please check the documentation for proper shipitfile formatting```

**Comment by tlartaud** [comment]
@jwhitmarsh I think that this issue is related to https://github.com/shipitjs/grunt-shipit/issues/58
Orchestrator is not binded correctly while using grunt-shipit.

That's why I had to remove the 'init' event from the plugin nodes I use and switch them to the 'deploy' event to make it work. See https://github.com/timkelty/shipit-shared/issues/32#issuecomment-145037233.
